# -*- coding: utf-8 -*-
"""Chase Dollander_srs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k-CvU02ip9e_aWR7U7ynnh9VIBFAIhFq
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from matplotlib.colors import Normalize
from matplotlib.colors import ListedColormap
from matplotlib.patches import Polygon


def plot_slg_heatmap(df, player_name, pitch_type, stand=None, coors_filter=None):
    """
    Plot a plate heat map for a player and pitch type,
    coloring points by estimated SLG on contact.

    Only includes pitches where description == 'hit_into_play'.

    Parameters:
        df : pd.DataFrame
        player_name : str
        pitch_type : str
    """

    # Ensure stand is always a list
    if stand is None:
        stand = ["R","L"]
    elif isinstance(stand, str):
        stand = [stand]

    # Handle coors
    if coors_filter is None:
        coors_filter = [0,1]
    elif isinstance(coors_filter, int):
        coors_filter = [coors_filter]

    # Filter data
    df_plot = df[
        (df['player_name'] == player_name) &
        (df['pitch_type'] == pitch_type) &
        (df['description'] == 'hit_into_play') &
        (df['stand'].isin(stand)) &
        (df['coors'].isin(coors_filter))
    ]


    if df_plot.empty:
        print(f"No data for {player_name} / {pitch_type} with hit_into_play")
        return

    plt.figure(figsize=(6,6))

    # Normalize SLG for color intensity
    norm = Normalize(vmin=df_plot['estimated_slg_using_speedangle'].min(),
                     vmax=df_plot['estimated_slg_using_speedangle'].max())


    # Scatter
    scatter = plt.scatter(
        df_plot['plate_x'],
        df_plot['plate_z'],
        c=df_plot['estimated_slg_using_speedangle'],
        cmap='Purples',
        norm=norm,
        s=60,
        alpha=0.7,
        edgecolor='black',
        linewidth=0.1
    )

    # Colorbar
    cbar = plt.colorbar(scatter)
    cbar.set_label("Expected SLG", fontsize=10)

    # Zone slug style
    text_style = dict(
    ha='left',
    va='top',
    fontsize=10,
    fontstyle='italic',
    color='darkgreen'
    )

    # Strike zone
    plate_half_width = 17 / 12 / 2
    zone_bottom = 1.5
    zone_top = 3.5
    strike_zone = patches.Rectangle(
        (-plate_half_width, zone_bottom),
        2 * plate_half_width,
        zone_top - zone_bottom,
        linewidth=2,
        edgecolor='Black',
        facecolor='none'
    )

    zone1 = patches.Rectangle(
        (-plate_half_width, zone_bottom + 2 *(zone_top - zone_bottom) / 3),
        2 * plate_half_width / 3,
        (zone_top - zone_bottom) / 3,
        edgecolor='Grey', facecolor='none', linewidth=.5, linestyle=':'
    )

    zone2 = patches.Rectangle(
        (-plate_half_width / 3, zone_bottom + 2 *(zone_top - zone_bottom) / 3),
        2 * plate_half_width / 3,
        (zone_top - zone_bottom) / 3,
        edgecolor='Grey', facecolor='none', linewidth=.5, linestyle=':'
    )

    zone3 = patches.Rectangle(
        (plate_half_width / 3, zone_bottom + 2 *(zone_top - zone_bottom) / 3),
        2 * plate_half_width / 3,
        (zone_top - zone_bottom) / 3,
        edgecolor='Grey', facecolor='none', linewidth=.5, linestyle=':'
    )

    zone4 = patches.Rectangle(
        (-plate_half_width, zone_bottom + (zone_top - zone_bottom) / 3),
        2 * plate_half_width / 3,
        (zone_top - zone_bottom) / 3,
        edgecolor='Grey', facecolor='none', linewidth=.5, linestyle=':'
    )

    zone5 = patches.Rectangle(
        (-plate_half_width / 3, zone_bottom + (zone_top - zone_bottom) / 3),
        2 * plate_half_width / 3,
        (zone_top - zone_bottom) / 3,
        edgecolor='Grey', facecolor='none', linewidth=.5, linestyle=':'
    )

    zone6 = patches.Rectangle(
        (plate_half_width / 3, zone_bottom + (zone_top - zone_bottom) / 3),
        2 * plate_half_width / 3,
        (zone_top - zone_bottom) / 3,
        edgecolor='Grey', facecolor='none', linewidth=.5, linestyle=':'
    )

    zone7 = patches.Rectangle(
        (-plate_half_width, zone_bottom),
        2 * plate_half_width / 3,
        (zone_top - zone_bottom) / 3,
        edgecolor='Grey', facecolor='none', linewidth=.5, linestyle=':'
    )

    zone8 = patches.Rectangle(
        (-plate_half_width / 3, zone_bottom),
        2 * plate_half_width / 3,
        (zone_top - zone_bottom) / 3,
        edgecolor='Grey', facecolor='none', linewidth=.5, linestyle=':'
    )

    zone9 = patches.Rectangle(
        (plate_half_width / 3, zone_bottom),
        2 * plate_half_width / 3,
        (zone_top - zone_bottom) / 3,
        edgecolor='Grey', facecolor='none', linewidth=.5, linestyle=':'
    )


    # Collect Zone slugs
    zone_slugs = {}

    for i in range(1, 15):
        avg_slg = (
            df_plot[df_plot["zone"] == i]["estimated_slg_using_speedangle"].mean()
        )
        zone_slugs[i] = round(avg_slg, 3)

    plt.gca().add_patch(strike_zone)
    plt.gca().add_patch(zone1)
    plt.gca().add_patch(zone2)
    plt.gca().add_patch(zone3)
    plt.gca().add_patch(zone4)
    plt.gca().add_patch(zone5)
    plt.gca().add_patch(zone6)
    plt.gca().add_patch(zone7)
    plt.gca().add_patch(zone8)
    plt.gca().add_patch(zone9)

    plt.text(
    -plate_half_width + 0.04, 0.10 + zone_bottom + 2 *(zone_top - zone_bottom) / 3,
    f"{zone_slugs[1]:.3f}",
    **text_style
    )

    plt.text(
    -plate_half_width / 3 + 0.04, 0.10 + zone_bottom + 2 *(zone_top - zone_bottom) / 3,
    f"{zone_slugs[2]:.3f}",
    **text_style
    )

    plt.text(
    plate_half_width / 3  + 0.04, 0.10 + zone_bottom + 2 *(zone_top - zone_bottom) / 3,
    f"{zone_slugs[3]:.3f}",
    **text_style
    )

    plt.text(
    -plate_half_width + 0.04, 0.10 +  zone_bottom + (zone_top - zone_bottom) / 3,
    f"{zone_slugs[4]:.3f}",
    **text_style
    )

    plt.text(
    0.04 + -plate_half_width / 3, 0.10 + zone_bottom + (zone_top - zone_bottom) / 3,
    f"{zone_slugs[5]:.3f}",
    **text_style
    )

    plt.text(
    0.04 + plate_half_width / 3, 0.10 + zone_bottom + (zone_top - zone_bottom) / 3,
    f"{zone_slugs[6]:.3f}",
    **text_style
    )

    plt.text(
    -plate_half_width + 0.04, 0.10 + zone_bottom,
    f"{zone_slugs[7]:.3f}",
    **text_style
    )

    plt.text(
    0.04 + -plate_half_width / 3, 0.10 + zone_bottom,
    f"{zone_slugs[8]:.3f}",
    **text_style
    )

    plt.text(
    0.04 + plate_half_width / 3, 0.10 + zone_bottom,
    f"{zone_slugs[9]:.3f}",
    **text_style
    )

    plt.text(
    -plate_half_width, zone_bottom - 0.20,
    "xSLG by zone",
    **text_style
    )

    # Formatting
    # Stand label
    if stand == ["R", "L"]:
        stand_label = "RHH & LHH"
    elif stand == ["R"]:
        stand_label = "RHH"
    elif stand == ["L"]:
        stand_label = "LHH"
    else:
        stand_label = "Mixed"

    # Coors label
    if coors_filter == [0,1]:
        coors_label = "All Parks"
    elif coors_filter == [1]:
        coors_label = "Coors Field"
    elif coors_filter == [0]:
        coors_label = "Non-Coors"
    else:
        coors_label = ""

    # Pitching label
    if pitch_type == "FF":
        pitch_type = "Fastball"
    elif pitch_type == "CU":
        pitch_type = "Curveball"

    plt.axis('off')
    plt.gca().set_aspect('equal', adjustable='box')
    plt.title(f"{player_name} - {pitch_type} \n {stand_label} | {coors_label} | xSLG Heat Map", fontsize=14)

    plt.show()




def plot_whiffs(df, player_name, pitch_type, stand=None, coors_filter=None):
    """
    Plot a plate heat map for a player and pitch type,
    coloring points by estimated SLG on contact.

    Only includes pitches where description == 'hit_into_play'.

    Parameters:
        df : pd.DataFrame
        player_name : str
        pitch_type : str
    """

    # Ensure stand is always a list
    if stand is None:
        stand = ["R","L"]
    elif isinstance(stand, str):
        stand = [stand]

    # Handle coors
    if coors_filter is None:
        coors_filter = [0,1]
    elif isinstance(coors_filter, int):
        coors_filter = [coors_filter]

    # Filter data
    df_plot = df[
        (df['player_name'] == player_name) &
        (df['pitch_type'] == pitch_type) &
        (df['plate_x'] > -2) & (df['plate_x'] < 2) &
        (df['plate_z'] > 1) & (df['plate_z'] < 4) &
        (df['stand'].isin(stand)) &
        (df['coors'].isin(coors_filter))
    ]


    if df_plot.empty:
        print(f"No data for {player_name} / {pitch_type}")
        return

    plt.figure(figsize=(8,8))

    cmap = ListedColormap(['lightgrey', 'purple'])

    # Scatter
    scatter = plt.scatter(
        df_plot['plate_x'],
        df_plot['plate_z'],
        c=df_plot['whiff'],
        cmap=cmap,
        s=60,
        alpha=0.7,
        edgecolor='black',
        linewidth=0.1
    )


    # Zone whiff style
    text_style = dict(
    ha='left',
    va='top',
    fontsize=12,
    fontstyle='italic',
    fontweight='bold',
    color='darkgreen'
    )

    # Strike zone
    plate_half_width = 17 / 12 / 2
    zone_bottom = 1.5
    zone_top = 3.5
    strike_zone = patches.Rectangle(
        (-plate_half_width, zone_bottom),
        2 * plate_half_width,
        zone_top - zone_bottom,
        linewidth=2,
        edgecolor='Black',
        facecolor='none'
    )

    zone1 = patches.Rectangle(
        (-plate_half_width, zone_bottom + 2 *(zone_top - zone_bottom) / 3),
        2 * plate_half_width / 3,
        (zone_top - zone_bottom) / 3,
        edgecolor='Grey', facecolor='none', linewidth=.5, linestyle=':'
    )

    zone2 = patches.Rectangle(
        (-plate_half_width / 3, zone_bottom + 2 *(zone_top - zone_bottom) / 3),
        2 * plate_half_width / 3,
        (zone_top - zone_bottom) / 3,
        edgecolor='Grey', facecolor='none', linewidth=.5, linestyle=':'
    )

    zone3 = patches.Rectangle(
        (plate_half_width / 3, zone_bottom + 2 *(zone_top - zone_bottom) / 3),
        2 * plate_half_width / 3,
        (zone_top - zone_bottom) / 3,
        edgecolor='Grey', facecolor='none', linewidth=.5, linestyle=':'
    )

    zone4 = patches.Rectangle(
        (-plate_half_width, zone_bottom + (zone_top - zone_bottom) / 3),
        2 * plate_half_width / 3,
        (zone_top - zone_bottom) / 3,
        edgecolor='Grey', facecolor='none', linewidth=.5, linestyle=':'
    )

    zone5 = patches.Rectangle(
        (-plate_half_width / 3, zone_bottom + (zone_top - zone_bottom) / 3),
        2 * plate_half_width / 3,
        (zone_top - zone_bottom) / 3,
        edgecolor='Grey', facecolor='none', linewidth=.5, linestyle=':'
    )

    zone6 = patches.Rectangle(
        (plate_half_width / 3, zone_bottom + (zone_top - zone_bottom) / 3),
        2 * plate_half_width / 3,
        (zone_top - zone_bottom) / 3,
        edgecolor='Grey', facecolor='none', linewidth=.5, linestyle=':'
    )

    zone7 = patches.Rectangle(
        (-plate_half_width, zone_bottom),
        2 * plate_half_width / 3,
        (zone_top - zone_bottom) / 3,
        edgecolor='Grey', facecolor='none', linewidth=.5, linestyle=':'
    )

    zone8 = patches.Rectangle(
        (-plate_half_width / 3, zone_bottom),
        2 * plate_half_width / 3,
        (zone_top - zone_bottom) / 3,
        edgecolor='Grey', facecolor='none', linewidth=.5, linestyle=':'
    )

    zone9 = patches.Rectangle(
        (plate_half_width / 3, zone_bottom),
        2 * plate_half_width / 3,
        (zone_top - zone_bottom) / 3,
        edgecolor='Grey', facecolor='none', linewidth=.5, linestyle=':'
    )

    # Outside Zones
    zone11_coords = [
        [-plate_half_width - .2, zone_bottom + (zone_top - zone_bottom) / 2],
        [-plate_half_width - .2, zone_bottom + (zone_top - zone_bottom) + .2],
        [0, zone_bottom + (zone_top - zone_bottom) + .2],
        [0, zone_bottom + (zone_top - zone_bottom)],
        [-plate_half_width, zone_bottom + (zone_top - zone_bottom)],
        [-plate_half_width, zone_bottom + (zone_top - zone_bottom) / 2]
    ]

    zone11 = Polygon(zone11_coords, closed=True, edgecolor='Black', facecolor='none', linewidth=.57, linestyle='-')

    zone12_coords = [
        [plate_half_width + .2, zone_bottom + (zone_top - zone_bottom) / 2],
        [plate_half_width + .2, zone_bottom + (zone_top - zone_bottom) + .2],
        [0, zone_bottom + (zone_top - zone_bottom) + .2],
        [0, zone_bottom + (zone_top - zone_bottom)],
        [plate_half_width, zone_bottom + (zone_top - zone_bottom)],
        [plate_half_width, zone_bottom + (zone_top - zone_bottom) / 2]
    ]

    zone12 = Polygon(zone12_coords, closed=True, edgecolor='Black', facecolor='none', linewidth=.57, linestyle='-')

    zone13_coords = [
        [plate_half_width + .2, zone_bottom + (zone_top - zone_bottom) / 2],
        [plate_half_width + .2, zone_bottom - .2],
        [0, zone_bottom - .2],
        [0, zone_bottom],
        [plate_half_width, zone_bottom],
        [plate_half_width, zone_bottom + (zone_top - zone_bottom) / 2]
    ]

    zone13 = Polygon(zone13_coords, closed=True, edgecolor='Black', facecolor='none', linewidth=.57, linestyle='-')

    zone14_coords = [
        [-plate_half_width - .2, zone_bottom + (zone_top - zone_bottom) / 2],
        [-plate_half_width - .2, zone_bottom - .2],
        [0, zone_bottom - .2],
        [0, zone_bottom],
        [-plate_half_width, zone_bottom],
        [-plate_half_width, zone_bottom + (zone_top - zone_bottom) / 2]
    ]

    zone14 = Polygon(zone14_coords, closed=True, edgecolor='Black', facecolor='none', linewidth=.57, linestyle='-')

    # Collect Zone Whiffs
    zone_whiff_perc = {}

    for i in range(1, 15):
        avg_slg = (
            df_plot[df_plot["zone"] == i]["whiff"].mean()
        )
        zone_whiff_perc[i] = round(avg_slg, 3)

    plt.gca().add_patch(strike_zone)
    plt.gca().add_patch(zone1)
    plt.gca().add_patch(zone2)
    plt.gca().add_patch(zone3)
    plt.gca().add_patch(zone4)
    plt.gca().add_patch(zone5)
    plt.gca().add_patch(zone6)
    plt.gca().add_patch(zone7)
    plt.gca().add_patch(zone8)
    plt.gca().add_patch(zone9)
    plt.gca().add_patch(zone11)
    plt.gca().add_patch(zone12)
    plt.gca().add_patch(zone13)
    plt.gca().add_patch(zone14)

    plt.text(
    -plate_half_width + 0.04, 0.12 + zone_bottom + 2 *(zone_top - zone_bottom) / 3,
    f"{zone_whiff_perc[1]:.3f}",
    **text_style
    )

    plt.text(
    -plate_half_width / 3 + 0.04, 0.12 + zone_bottom + 2 *(zone_top - zone_bottom) / 3,
    f"{zone_whiff_perc[2]:.3f}",
    **text_style
    )

    plt.text(
    plate_half_width / 3  + 0.04, 0.12 + zone_bottom + 2 *(zone_top - zone_bottom) / 3,
    f"{zone_whiff_perc[3]:.3f}",
    **text_style
    )

    plt.text(
    -plate_half_width + 0.04, 0.12 +  zone_bottom + (zone_top - zone_bottom) / 3,
    f"{zone_whiff_perc[4]:.3f}",
    **text_style
    )

    plt.text(
    0.04 + -plate_half_width / 3, 0.12 + zone_bottom + (zone_top - zone_bottom) / 3,
    f"{zone_whiff_perc[5]:.3f}",
    **text_style
    )

    plt.text(
    0.04 + plate_half_width / 3, 0.12 + zone_bottom + (zone_top - zone_bottom) / 3,
    f"{zone_whiff_perc[6]:.3f}",
    **text_style
    )

    plt.text(
    -plate_half_width + 0.04, 0.12 + zone_bottom,
    f"{zone_whiff_perc[7]:.3f}",
    **text_style
    )

    plt.text(
    0.04 + -plate_half_width / 3, 0.12 + zone_bottom,
    f"{zone_whiff_perc[8]:.3f}",
    **text_style
    )

    plt.text(
    0.04 + plate_half_width / 3, 0.12 + zone_bottom,
    f"{zone_whiff_perc[9]:.3f}",
    **text_style
    )

    plt.text(
    -plate_half_width - 0.15, zone_top + 0.15,
    f"{zone_whiff_perc[11]:.3f}",
    **text_style
    )

    plt.text(
    plate_half_width - 0.19, zone_top + 0.15,
    f"{zone_whiff_perc[12]:.3f}",
    **text_style
    )

    plt.text(
    -plate_half_width - 0.15, zone_bottom - 0.08,
    f"{zone_whiff_perc[13]:.3f}",
    **text_style
    )

    plt.text(
    plate_half_width - 0.18, zone_bottom - 0.08,
    f"{zone_whiff_perc[14]:.3f}",
    **text_style
    )

    plt.text(
    -plate_half_width - 0.20, zone_bottom - 0.40,
    "Whiff % by zone",
    **text_style
    )



    # Formatting
    # Stand label
    if stand == ["R", "L"]:
        stand_label = "RHH & LHH"
    elif stand == ["R"]:
        stand_label = "RHH"
    elif stand == ["L"]:
        stand_label = "LHH"
    else:
        stand_label = "Mixed"

    # Coors label
    if coors_filter == [0,1]:
        coors_label = "All Parks"
    elif coors_filter == [1]:
        coors_label = "Coors Field"
    elif coors_filter == [0]:
        coors_label = "Non-Coors"
    else:
        coors_label = ""

    # Pitching label
    if pitch_type == "FF":
        pitch_type = "Fastball"
    elif pitch_type == "CU":
        pitch_type = "Curveball"


    plt.axis('off')
    plt.gca().set_aspect('equal', adjustable='box')
    plt.title(f"{player_name} - {pitch_type} \n {stand_label} | {coors_label} | Whiffs by zone", fontsize=14)

    plt.show()


def pitcher_splits(df, player_name, stand=None, pitch_type=None, ):
    # Remove pitches not resulting in event
    df = df[df['events'].notna()]
    df = df[df['events'] != 'truncated_pa']

    # Handle stand
    if stand is None:
        stand = ["R","L"]

    # Ensure stand is always a list
    if stand is None:
        stand = ["R","L"]
    elif isinstance(stand, str):
        stand = [stand]

    # Base filter
    base_filter = (
        (df['player_name'] == player_name) &
        (df['stand'].isin(stand))
    )

    # Optionally filter by pitch_type if provided
    if pitch_type is not None:
        base_filter &= (df['pitch_type'] == pitch_type)

    # Split by home/road
    df_splits_home = df[base_filter & (df['coors'] == 1)]
    df_splits_road = df[base_filter & (df['coors'] == 0)]

    ## Batting Average
    hit = ['single', 'double', 'triple', 'home_run']
    non_at_bat = ['walk', 'hit_by_pitch', 'sac_fly', 'intent_walk', 'sac_bunt', 'catcher_interf', 'sac_bunt_double_play', 'truncated_pa', 'sac_fly_double_play']


    batting_avg_home = (
      df_splits_home[df_splits_home['events'].isin(hit)].shape[0] /
      df_splits_home[~df_splits_home['events'].isin(non_at_bat)].shape[0]
    )

    batting_avg_road = (
        df_splits_road[df_splits_road['events'].isin(hit)].shape[0] /
        df_splits_road[~df_splits_road['events'].isin(non_at_bat)].shape[0]
    )

    ## On Base percentage
    on_base = ['single', 'double', 'triple', 'home_run', 'walk', 'intent_walk', 'hit_by_pitch']
    obp_denominator_extra = ['sac_bunt', 'catcher_interf', 'sac_bunt_double_play', 'truncated_pa']

    on_base_per_home = (
        df_splits_home[df_splits_home['events'].isin(on_base)].shape[0] /
        df_splits_home[~df_splits_home['events'].isin(obp_denominator_extra)].shape[0]
    )

    on_base_per_road = (
        df_splits_road[df_splits_road['events'].isin(on_base)].shape[0] /
        df_splits_road[~df_splits_road['events'].isin(obp_denominator_extra)].shape[0]
    )

    ## Slugging Percentage
    slugging = {'single': 1, 'double': 2, 'triple': 3, 'home_run': 4}

    slugging_numerator_home = sum(df_splits_home['events'].map(slugging).fillna(0))
    slugging_numerator_road = sum(df_splits_road['events'].map(slugging).fillna(0))

    slgging_per_home = (
        slugging_numerator_home /
        df_splits_home[~df_splits_home['events'].isin(non_at_bat)].shape[0]
    )

    slgging_per_road = (
        slugging_numerator_road /
        df_splits_road[~df_splits_road['events'].isin(non_at_bat)].shape[0]
    )

    return {
        'batting_avg_home': batting_avg_home,
        'batting_avg_road': batting_avg_road,
        'obp_home': on_base_per_home,
        'obp_road': on_base_per_road,
        'slugging_home': slgging_per_home,
        'slugging_road': slgging_per_road
    }




def pitch_movement_delta(player_name, df):
    """
    Compute Euclidean distance between mean pfx_x / pfx_z at Coors vs Other Parks
    for each pitch type for a given pitcher.

    Returns a DataFrame with pitch_type, coors_mean_x, coors_mean_z, other_mean_x,
    other_mean_z, and euclidean_delta.
    """

    pitcher_df = df[df['player_name'] == player_name].copy()
    if pitcher_df.empty:
        print(f"No data for {player_name}")
        return None

    # Convert to inches and flip horizontal to match Savant orientation
    pitcher_df['pfx_x_plot'] = -pitcher_df['pfx_x'] * 12
    pitcher_df['pfx_z_plot'] = pitcher_df['pfx_z'] * 12

    results = []

    for pitch, group in pitcher_df.groupby('pitch_type'):
        coors = group[group['coors'] == 1]
        other = group[group['coors'] == 0]

        if len(coors) < 5 or len(other) < 5:
            continue  # skip if not enough samples

        coors_mean_x = coors['pfx_x_plot'].mean()
        coors_mean_z = coors['pfx_z_plot'].mean()

        other_mean_x = other['pfx_x_plot'].mean()
        other_mean_z = other['pfx_z_plot'].mean()

        euclidean_delta = np.sqrt(
            (coors_mean_x - other_mean_x)**2 + (coors_mean_z - other_mean_z)**2
        )

        results.append({
            'pitch_type': pitch,
            'coors_mean_x': coors_mean_x,
            'coors_mean_z': coors_mean_z,
            'other_mean_x': other_mean_x,
            'other_mean_z': other_mean_z,
            'euclidean_delta': euclidean_delta
        })

    return pd.DataFrame(results).sort_values('euclidean_delta', ascending=False)



def savant_pitch_metrics(df, player_name, pitch_type=None, stand=None):
    """
    Compute and retrun baseball savant style pitch statistics for a given pitcher.
    Pitch type and handedness can be filtered.
    home and road splits will be given
    """
    df = df[df['player_name'] == player_name]

    # handle batter handedness
    if stand is not None:
        if isinstance(stand, str):
            stand = [stand]
        df = df[df['stand'].isin(stand)]

    # handle pitch type
    if pitch_type is not None:
        df = df[df['pitch_type'] == pitch_type]

    # terminal pitches (end of PA)
    pa_df = df[df['events'].notna()].copy()

    # Split by home/road
    df_splits_home = pa_df[pa_df['coors'] == 1]
    df_splits_road = pa_df[pa_df['coors'] == 0]

    # event groups
    hits = ['single','double','triple','home_run']

    ab_events = [
        'single','double','triple','home_run',
        'field_out','force_out','grounded_into_double_play',
        'field_error','fielders_choice','strikeout', 'double_play',
        'fielders_choice_out', 'strikeout_double_play', 'triple_play'
    ]

    bip_events = [
        'single','double','triple','home_run',
        'field_out','force_out','grounded_into_double_play',
        'field_error','fielders_choice', 'double_play',
        'fielders_choice_out', 'triple_play'
    ]

    walk_events = ['walk','intent_walk']
    hbp_events = ['hit_by_pitch']
    sac_events = ['sac_fly']

    # AB
    ab_df_home = df_splits_home[df_splits_home['events'].isin(ab_events)]
    AB_home = len(ab_df_home)
    ab_df_road = df_splits_road[df_splits_road['events'].isin(ab_events)]
    AB_road = len(ab_df_road)

    # hits
    H_home = df_splits_home[df_splits_home['events'].isin(hits)].shape[0]
    H_road = df_splits_road[df_splits_road['events'].isin(hits)].shape[0]

    # total bases
    bases = {'single':1,'double':2,'triple':3,'home_run':4}
    TB_home = df_splits_home['events'].map(bases).fillna(0).sum()
    TB_road = df_splits_road['events'].map(bases).fillna(0).sum()

    # walks / hbp / sac
    BB_home = df_splits_home[df_splits_home['events'].isin(walk_events)].shape[0]
    BB_road = df_splits_road[df_splits_road['events'].isin(walk_events)].shape[0]

    HBP_home = df_splits_home[df_splits_home['events'].isin(hbp_events)].shape[0]
    HBP_road = df_splits_road[df_splits_road['events'].isin(hbp_events)].shape[0]

    SF_home = df_splits_home[df_splits_home['events'].isin(sac_events)].shape[0]
    SF_road = df_splits_road[df_splits_road['events'].isin(sac_events)].shape[0]

    # PA
    PA_home = AB_home + BB_home + HBP_home + SF_home
    PA_road = AB_road + BB_road + HBP_road + SF_road

    # BIP
    bip_df_home = df_splits_home[df_splits_home['events'].isin(bip_events)]
    bip_df_road = df_splits_road[df_splits_road['events'].isin(bip_events)]
    BIP_home = len(bip_df_home)
    BIP_road = len(bip_df_road)

    #Expected Stats
    xBA_tot_home = df_splits_home['estimated_ba_using_speedangle'].sum()
    xBA_tot_road = df_splits_road['estimated_ba_using_speedangle'].sum()

    xSLG_tot_home = df_splits_home['estimated_slg_using_speedangle'].sum()
    xSLG_tot_road = df_splits_road['estimated_slg_using_speedangle'].sum()

    xBA_home = xBA_tot_home / AB_home if AB_home else None
    xBA_road = xBA_tot_road / AB_road if AB_road else None

    xSLG_home = xSLG_tot_home / AB_home if AB_home else None
    xSLG_road = xSLG_tot_road / AB_road if AB_road else None

    # final metrics
    BA_home = H_home / AB_home if AB_home else None
    BA_road = H_road / AB_road if AB_road else None
    SLG_home = TB_home / AB_home if AB_home else None
    SLG_road = TB_road / AB_road if AB_road else None

    print(f"Home BA: {BA_home:.3f}")
    print(f"Home SLG: {SLG_home:.3f}")
    print(f"Home xBA: {xBA_home:.3f}")
    print(f"Home xSLG: {xSLG_home:.3f}")
    print(".....................")
    print(f"Road BA: {BA_road:.3f}")
    print(f"Road SLG: {SLG_road:.3f}")
    print(f"Road xBA: {xBA_road:.3f}")
    print(f"Road xSLG: {xSLG_road:.3f}")

